.TH mp3server 1 "18 February 2013" "0.1"
.SH NAME
mp3server \- A mp3 re-streaming server
.SH SYNOPSIS
.B mp3server
.SH DESCRIPTION
Lorem ipsum dolor sit amet.

Consectetuer adipiscing elit.
.SH OPTIONS
.TP
.BI --version
Print version information.
.SH BUGS
No known bugs.
.SH AUTHORS
klaxa <email@hidden>
.br
SeanMcG <email@hidden>
