name: build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            cc: clang
          - os: ubuntu-latest
            cc: gcc
          - os: macos-latest
            cc: clang
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2

    - name: Install macOS dependencies
      if: runner.os == 'macOS'
      run: |
        brew install autoconf automake

    - name: Execute build
      env:
        CC: ${{ matrix.cc }}
      run: |
        ./bootstrap
        mkdir build
        cd build
        ../configure
        make
